backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: homepage
    label: Homepage
    file: src/pages/homepage/index.md
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: home-page}
      - {label: Certifications List, name: certifications, widget: list, fields: [{label: Image, name: certImage, widget: image}, {label: Description, name: description, widget: string}]}

  - name: settings
    label: Settings
    file: src/pages/settings/index.md
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: settings}
      - {label: Navigation Menu, name: nav, widget: list, fields: [{label: Label, name: label, widget: string}, {label: URL, name: url, widget: string}, {label: Child Menu, name: children, widget: list, fields: [{label: Label, name: label, widget: string}, {label: URL, name: url, widget: string}]}]}

  - name: pages
    label: Pages
    folder: src/pages/pages
    create: true
    slug: "{{slug}}"
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: page}
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Body, name: body, widget: markdown}

  - name: services-page
    label: Services
    file: "src/pages/services/index.md"
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: services-page}
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Projects, name: projects, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Location, name: location, widget: object, fields: [{label: Latitude, name: lat, widget: string}, {label: Longitude, name: long, widget: string}]}, {label: Units, name: units, widget: number}, {label: Type, name: type, widget: select, options: ["Energy Audit", "Energy Audit Review", "Energy Star", "National Green Building Standard"]}]}
      - {label: Body, name: body, widget: markdown}

